language: python
dist: bionic

python:
  - 3.7

git:
  submodules: false

before_install:
  # cannot use SSH to fetch submodule
  - sed -i 's#git@github.com:#https://github.com/#' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

scripts:
  - qgis-plugin-ci -v

env:
  global:
    # OSGEO_USERNAME
    - secure: "fvptHzANZyz5/RoeFbuj2EymCWGEQBniDb+auTT6S+7DndVDkIAnYp3gTAEl9TbjD6fmKvdOiAKqezvuiedNY/FJMFN9pxKBWg1dKFzuDfbWJpF8+beTF93uQqXSKbeAJxRYz/FrJ0IgNKg16TJx/f42NTCoR22mr/xm9bD2HQbYCpWwnHwtRhDNA/JwSqbgpzx1XfFPEXFwn5EEQGfc49amm3gCVg4XMw06y/G0jGu/yG52tqQTDgPNN916UZo4PkJcDd+n/FQQ0DKx02RcTE59fuU5IljdPnYu/xgzGG9QfqTZ6x0mKefFYJ9JFnWDNRcxoSmiCpzXr2coPbasVer4Vaqk+9BGNuMOOqiQoEqqH7iknDmdx+pV16qa4CzO7poDcTAofufAqm0cDjNtzf8L6JtvJYgRSYP9lqL/rTzo/NqAgxmpJvMNqO8t5JBQT8GVAuniRJzlXHeZeYSgMWkQFKqojJd6Pgd2yxRY50J8S2JOZU+2xC/+Suv3RnuM5LDaMCDqNx7YAfJEumdQPVyXqbl8mOEQXbUGvCbrhogZ87RjoKmiLW4GoAvWdcphmIwUpxXMx4DV1c2UO91FXOsztbCLjv14ou/dB5sGI1VEepPY42CGlbwRRfVPcH6PASxjerhCCNRoL82YJ3PoUoRZmmk+1DROmKnXPLIaCE8="
    # OSGEO_PASSWORD
    - secure: "ZFVVZVXWCtQJYzSBMFoJbgkiBMmlk2wGkfSUUZhEjGlaZExyl7aVvY35rfNyI1iWE2c0uILYxhkB1UrEeKmKr2E37nivahBqmqZd1ZOphmnBd+scy/onaz1tReJi60cHZUG3GgCDCp7P7z63We5z2mwWKVAXSruPAzEtbZd5efbZM4w2Abf+EbuhR+dD3zZpUvbikn5ujG8KByd7lyncMxc8RylAoPuyK0Q4NooaODHqPoGFq1sgJBWgxCiPgPu19tsqHbMDCcMniZ9SzYO3cAfv0DE4bCwsL9L3UNBy9lSYfuQaz1buoLVhCOImA41ovuNgMd0nd5TAyZnwAqi7vgH+yxQ1is5p2/ZEzJ58GocZegEnYzZYeLUBdOOuyBKvZl/nOBo4nFULzrjRogCt0j0RXS3HLcE6LWQrw8yXKn5pMZCZqVK/SLHpkYFMaUa6Fj1s8VGRPHzVMesfVb8QBKVYdFNMi/T3oM++qC7QDWeRuOh9hzQpqG8c+IZlePQMibEgAkffLgrNGMjsB5ECjxv6Kb5HSjpsTEhVTfI7iQi1pXqqnVgOm51MXnK32Hj2yDR+WIk+1P5ayfDI4HuMVHtpU4WXfBgMP4kAy5vE0GSszWS+H8iYsCgGm/QOSA4rRtPp+ilGQtGiuxQjGFR22U82MA24mfDdadfWMxEdDk4="
    # TX_TOKEN
    - secure: "gOHdCFGyEh8ehqznrMWWQQGbodBAlqS2oVVCkq8iY8uDmOO76ilmM4CjBG5y01JVC5alcwf6482jACPQQP2yATzjIqwVhB49KaJEEH/N87/naChC2QkDVOkPuhZ3yZ6duoj9WWQrgd/Ba/g1a1x3lllwxx5yqJH35dqI5Mp+PWPdu52sHILwqAZbHV/UriT+PfFTwKN56RP8RB/nUWESGIB5KfBD89lh7Hzpf/ZtqGiZq/PBKWetRPfYKz1R6N3xuuJ6n4wETe8vmjgLnWNlx6rRDMFhw3GQQEjNtkBM0UlakD/wJbdweSMGdzIB7fKWsE9ESj1cku9QRcnaDY1SL53fCUkUClE46gx6bL/jC8WGL1yVcXCBshyBYTW6RA/EZhWBQmo22+zcogB9MU5gQn/qH7essd8i6bf6s9Nk7fM/3EW7miyg43jt4hGTlRC12WSCwKjVdgSGDGZf0zCmaQgGkfsHoL3+jO9K3skRIdyRYT5IvDafrk4f7qCq5MOLlao8jKguI75TG/SYrIGfU1kQ+U3qJZkmuEzDq3eJUCKdSZq+cvSztTOv/E7TyRzkQhdF6SChsUMGiSidOqU7N8eWdy5KKa9EJE3sGdd77teoTaJAb5Ey/ua4MYfB1rKk8g+2wzF+gkjOK5Z+3hnxZF7jqjbz1vo2wwWFQA34zHY="
    # GH_TOKEN
    - secure: "dWDL9BKgVjI6mYQUg8TNYUUs1a/yfCTFtAvChJo+My+EGzX/QUvuwKL0gBhIIs/Y4FKFNqh7VFx0L2h/gJeN7caA74wCxhQpIMOVkp/u4SydJPbi4MSXjltoubIZysBKelQVkeQkM3A2qqbJtqWcIfgSRwj/unFEMcsnHBEoctDVktirR1x94lUaIR+Dkd09odRnKObrGRqtUJNWLQEQW54O2ZcLVJisn1fc9gpCIyJAWCSA7LTcOJbLdiO1Bs2kNraB0LN9nFV1bWbbGimkRGQWcrDPmnT3WufI3okj7MWnAebQbdj48YabuQZjafpJOpSFx29q5AcV+rfNGTSL3hivMuUwNWXdI681i+h2yHLP+DGTuYFYK8Nhys+Cm6hNkz2T4HMwFLo5fw/AGlV90BAjbKxLSrKmDGXLzULkIDomiTZDrzf2RjiFtOt2AlGg2/8sGw0EmsCkyedFf7/ESxlSXxHMxN5K2tu0JLz/7xoGFvgDfJXE2lunYnzNGLCv1eSCLVAyq/KF/xIj7ZCecLUYlW7gCRcKqULWHzUNFye559dDb9u3QHGOLaajMmCZEKH+T+fi5zl2RgT8fedar6bQNY0HfPHxhazrrMVsaSNPeF6vALUd6oypfkHddKBOgMpHcLEcJ9d09CnEBUoBxdExg7qt+QV32INAuCFfufI="


jobs:
  include:
    - stage: push-translation
      if: branch = master AND repo = QGEP/qgis_wincan2qgep
      script: qgis-plugin-ci push-translation ${TX_TOKEN}

    - stage: deploy
      if: tag IS present AND repo = QGEP/qgis_wincan2qgep
      script: qgis-plugin-ci release ${TRAVIS_TAG} --transifex-token ${TX_TOKEN} --github-token ${GH_TOKEN} --create-plugin-repo --osgeo-username ${OSGEO_USERNAME} --osgeo-password ${OSGEO_PASSWORD}

