language: python

python:
  - 3.7

git:
  submodules: false

before_install:
  # cannot use SSH to fetch submodule
  - sed -i 's#git@github.com:#https://github.com/#' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

scripts:
  - qgis-plugin-ci -v

jobs:
  include:
    - stage: push-translation
      if: branch = master AND repo = QGEP/qgis_wincan2qgep
      script: qgis-plugin-ci push-translation ${TX_TOKEN}

    - stage: deploy
      if: tag IS present AND repo = QGEP/qgis_wincan2qgep
      script: qgis-plugin-ci release ${TRAVIS_TAG} --transifex-token ${TX_TOKEN} --github-token ${GH_TOKEN} --create-plugin-repo --osgeo-username ${OSGEO_USERNAME} --osgeo-password ${OSGEO_PASSWORD}

env:
  global:
    # OSGEO_USERNAME
    - secure: "fvptHzANZyz5/RoeFbuj2EymCWGEQBniDb+auTT6S+7DndVDkIAnYp3gTAEl9TbjD6fmKvdOiAKqezvuiedNY/FJMFN9pxKBWg1dKFzuDfbWJpF8+beTF93uQqXSKbeAJxRYz/FrJ0IgNKg16TJx/f42NTCoR22mr/xm9bD2HQbYCpWwnHwtRhDNA/JwSqbgpzx1XfFPEXFwn5EEQGfc49amm3gCVg4XMw06y/G0jGu/yG52tqQTDgPNN916UZo4PkJcDd+n/FQQ0DKx02RcTE59fuU5IljdPnYu/xgzGG9QfqTZ6x0mKefFYJ9JFnWDNRcxoSmiCpzXr2coPbasVer4Vaqk+9BGNuMOOqiQoEqqH7iknDmdx+pV16qa4CzO7poDcTAofufAqm0cDjNtzf8L6JtvJYgRSYP9lqL/rTzo/NqAgxmpJvMNqO8t5JBQT8GVAuniRJzlXHeZeYSgMWkQFKqojJd6Pgd2yxRY50J8S2JOZU+2xC/+Suv3RnuM5LDaMCDqNx7YAfJEumdQPVyXqbl8mOEQXbUGvCbrhogZ87RjoKmiLW4GoAvWdcphmIwUpxXMx4DV1c2UO91FXOsztbCLjv14ou/dB5sGI1VEepPY42CGlbwRRfVPcH6PASxjerhCCNRoL82YJ3PoUoRZmmk+1DROmKnXPLIaCE8="
    # OSGEO_PASSWORD
    - secure: "ZFVVZVXWCtQJYzSBMFoJbgkiBMmlk2wGkfSUUZhEjGlaZExyl7aVvY35rfNyI1iWE2c0uILYxhkB1UrEeKmKr2E37nivahBqmqZd1ZOphmnBd+scy/onaz1tReJi60cHZUG3GgCDCp7P7z63We5z2mwWKVAXSruPAzEtbZd5efbZM4w2Abf+EbuhR+dD3zZpUvbikn5ujG8KByd7lyncMxc8RylAoPuyK0Q4NooaODHqPoGFq1sgJBWgxCiPgPu19tsqHbMDCcMniZ9SzYO3cAfv0DE4bCwsL9L3UNBy9lSYfuQaz1buoLVhCOImA41ovuNgMd0nd5TAyZnwAqi7vgH+yxQ1is5p2/ZEzJ58GocZegEnYzZYeLUBdOOuyBKvZl/nOBo4nFULzrjRogCt0j0RXS3HLcE6LWQrw8yXKn5pMZCZqVK/SLHpkYFMaUa6Fj1s8VGRPHzVMesfVb8QBKVYdFNMi/T3oM++qC7QDWeRuOh9hzQpqG8c+IZlePQMibEgAkffLgrNGMjsB5ECjxv6Kb5HSjpsTEhVTfI7iQi1pXqqnVgOm51MXnK32Hj2yDR+WIk+1P5ayfDI4HuMVHtpU4WXfBgMP4kAy5vE0GSszWS+H8iYsCgGm/QOSA4rRtPp+ilGQtGiuxQjGFR22U82MA24mfDdadfWMxEdDk4="
    # TX_TOKEN
    -  secure: "Cg5E6mNAgTpztQ08G6VJP/05hKJ+x9O6kwrg5Vu01+jNJodZuHR5pdmwyXl2XuGrAfUGUV5kGajeHgikH63+APtejqenu3/kXFChRSIWKbRZ+8oiPQBQifhWVQGk8R+KBn9zKHXmOUAl7J8HoLCDrSiwTyB0Fat07sxVDEG0z2vm7fhJ5JoNJBk/CP3hUo06UhwnuOZj2KoWWiwhOpSAbollP2+zZqPmJrLg/YLmjIJwl3HSg34LokmWwX3z0cZ/Z6QKxQxngnlebVXe5P13tYw1a5uVKiUvVGJPGyyijB+5zvqyP7wUxKTs8JNekbVof95THrvVKEh++dmwp0E8ICTNtb2TiU6E6R9eq4mSMig6yTFauGIYCHBuRYrg3xrNem9M/PzxEZT/4pW6UuucqLWXOkIj3EUpoBOXfzExbrJoXWDnv0OCRPUOoKOUYQmmAcUfhrPDtjUN8j+v4SJEiv/uzMCl9RnWB6x8eulj8nyFrzPOxJ/ApolC+WHF9ICv0tJwnAdztqEKFTG2BBRQXbwwAZZRjGKsBq8FcXQxuRXuFiapFApBwo5hMtmaJEZkvAYBQ1d/rR3yrXlrvuHtizYWIlWgmIvX0TdBoPcuBpkxjLmhe2vbndAQbWOsmIDvdFvGK5NVMHG4avncaU4aueXAkSD5TMcUVyLQUYdZ61s="
    # GH_TOKEN
    - secure: "dWDL9BKgVjI6mYQUg8TNYUUs1a/yfCTFtAvChJo+My+EGzX/QUvuwKL0gBhIIs/Y4FKFNqh7VFx0L2h/gJeN7caA74wCxhQpIMOVkp/u4SydJPbi4MSXjltoubIZysBKelQVkeQkM3A2qqbJtqWcIfgSRwj/unFEMcsnHBEoctDVktirR1x94lUaIR+Dkd09odRnKObrGRqtUJNWLQEQW54O2ZcLVJisn1fc9gpCIyJAWCSA7LTcOJbLdiO1Bs2kNraB0LN9nFV1bWbbGimkRGQWcrDPmnT3WufI3okj7MWnAebQbdj48YabuQZjafpJOpSFx29q5AcV+rfNGTSL3hivMuUwNWXdI681i+h2yHLP+DGTuYFYK8Nhys+Cm6hNkz2T4HMwFLo5fw/AGlV90BAjbKxLSrKmDGXLzULkIDomiTZDrzf2RjiFtOt2AlGg2/8sGw0EmsCkyedFf7/ESxlSXxHMxN5K2tu0JLz/7xoGFvgDfJXE2lunYnzNGLCv1eSCLVAyq/KF/xIj7ZCecLUYlW7gCRcKqULWHzUNFye559dDb9u3QHGOLaajMmCZEKH+T+fi5zl2RgT8fedar6bQNY0HfPHxhazrrMVsaSNPeF6vALUd6oypfkHddKBOgMpHcLEcJ9d09CnEBUoBxdExg7qt+QV32INAuCFfufI="
